### ISSUE TITLE
Im Facing an issue while applying query on search text

### ISSUE THREAD

**Issue by Taimoor-Azam** [dariopellegrini/StorageDone-Android#8]
is there any way to apply like operator on item name with case insensitive  ?

**Comment by dariopellegrini** [comment]
Hello @Taimoor-Azam.
Thank you for your response.
This is similar to a recent iOS issue.

I'm pasting here the same response.
Unfortunately, like operator is case sensitive, so there is no way to make a case insensitive query at the moment.

By the way, you have different options.

### Use a lowercased field
```kotlin
data class Teacher(
    val id: Int,
    val name: String) {
    val lowercasedName = name.lowercased()
}
...

val teachers = database.get<Teacher>("lowercasedName".like("si%")) // Use lowercase-only queries
```

### Use regex
As well the operator "like", regex is case sensitive. Then due to the C++ lower layer regex engine, modifiers like `i` for regex are not available.  
You can still achieve a case-insensitive query using regex text intervals.
```kotlin
// Search for everything that has a name starting with "ang" case insensitive (ex: "Angela", "Angely")
val teachers = database.get<Teacher>("name".regex("[aA][nN][gG].*"))
```

### Use the last committed version of StorageDone-Android
The last committed version of StorageDone-Android supports case-insensitive like.

```
implementation 'com.github.dariopellegrini:StorageDone-Android:ecb1528dcf'
```

```kotlin
val teachers = database.get<Teacher>("name".like("si%", caseInsensitive = true))
```

Hope this helps.

Thank you.
